import { render } from '@testing-library/react';
import RootLayout, { metadata } from '../layout';

// Mock next/font/google
jest.mock('next/font/google', () => ({
  Inter: () => ({
    variable: 'mock-font-class',
  }),
}));

describe('RootLayout', () => {
  it('renders with correct structure and classes', () => {
    const { container } = render(
      <div id="__next">
        <RootLayout>
          <div data-testid="child">Test Content</div>
        </RootLayout>
      </div>
    );

    const body = container.querySelector('body');
    expect(body?.className).toContain('mock-font-class');
    expect(body?.className).toContain('font-sans');
    expect(body?.className).toContain('antialiased');
    expect(container).toHaveTextContent('Test Content');
  });

  it('renders metadata correctly', () => {
    expect(metadata).toEqual({
      title: 'Create Next App',
      description: 'Generated by create next app',
    });
  });
});
